use_frameworks!

platform :ios, '9.0'

target 'ImageAnalyzerService_Example' do
  pod 'ImageAnalyzerService', :path => '../'

  target 'ImageAnalyzerService_Tests' do
    inherit! :search_paths

    
  end
end
